# Generated by Django 6.1.1 on 2026-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_service',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=35)),
                ('customer_no', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
